name: "Infrastructure stack delete"

on:
  workflow_dispatch:
    inputs:
      confirmRun:
        description: 'Confirm if you want to delete stack'
        required: true
        #default: false
        type: boolean
      environment:
        description: 'What stack to delete'
        type: environment
        required: true

jobs:
  check_aws_secrets:
    uses: ./.github/workflows/aws_check_secrets.yml

  terraform:
    name: "CI/CD Infrastructure Delete Workflow"
    runs-on: ubuntu-latest
    needs: [check_aws_secrets]
    if: |
      ${{ inputs.confirmRun }} &&
      needs.checksecret.outputs.is_AWS_ACCESS_KEY_ID_set == 'true' &&
      needs.checksecret.outputs.is_AWS_SECRET_ACCESS_KEY_set == 'true'
    environment: ${{ inputs.environment }}
    env:
      TFSTATE_BUCKET: ${{ secrets.TFSTATE_BUCKET }}
      TFSTATE_REGION: ${{ env.AWS_DEFAULT_REGION }}
      TFSTATE_KEY: 'stacks/${{ env.GITHUB_REPOSITORY }}-${{ inputs.environment }}'

    steps:
      - name: Checkout the repository to the runner
        uses: actions/checkout@v3

      - name: Set common environment variables
        run: grep -v "^#" .github/.env >> $GITHUB_ENV

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_DEFAULT_REGION }}

      - name: Setup Terraform with specified version on the runner
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: ${{ env.TERRAFORM_VERSION }}

      - name: Setup directory
        working-directory: ./terraform
        run: pwd

      - name: Terraform init
        id: init
        run: ../.github/scripts/terraform-with-backend.sh
        env:
          TFSTATE_BUCKET: ${{ env.TFSTATE_BUCKET }}
          TFSTATE_REGION: ${{ env.AWS_DEFAULT_REGION }}
          TFSTATE_KEY: stacks/${{ env.GITHUB_REPOSITORY }}

      - name: Terraform destroy
        id: destroy
        run: terraform destroy -auto-approve -no-color -input=false
        continue-on-error: true
